qarysite/qary_app/urls.py
# from django.contrib import admin
# from django.urls import path
from django.conf.urls import url  # , include

from qary_app import views


app_name = 'qary_app'


urlpatterns = [
    # path('', home_view),
    url(r'^$', views.PostListView.as_view(), name='list'),
    url(r'^(?P<pk>[-\w]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'answer/', views.reply, name='answer'),
    url(r'question/', views.home_view, name='question'),

]

qarysite/qarysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from qary_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home_view),
    url(r'^qary_app/', include('qary_app.urls', namespace='qary_app')),
    url(r'question/', views.home_view, name='question'),
    url(r'answer/', views.reply, name='answer'),

]

qarysite/qary_app/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    text = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={pk: self.pk})

qarysite/qary_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from qary_app import models
from qary.clibot import CLIBot
# import re  # noqa


bot = CLIBot(bots=('glossary',))

get_request = None


def home_view(request):

    # function return Query.dict from GET
    global get_request
    get_request = request.GET

    return render(request, "question.html", )


def reply(request):

    # k = str(n[20:-4])
    bot_reply = bot.reply(get_request['n'])

    dict_1 = {'insert': bot_reply, 'Question': get_request['n']}

    return render(request, "answer.html", context=dict_1)


class PostListView(ListView):
    context_object_name = 'posts'
    model = models.Post


class PostDetailView(DetailView):
    context_object_name = 'post_detail'
    model = models.Post
    template_name = 'qary_app/first_app_detail.html'

qarysite/qary_app/templates/qary_app/first_app_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Django-Project</title>
</head>
<body>
<div class="navbar navbar-dark bg-dark">
    <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'qary_app:list'%}">Posts</a>
    <a class="navbar-brand "href="{% url 'admin:index'%}">Admin</a>
    <a class="navbar-brand "href="{% url 'question'%}">Bot</a>
    <a class="navbar-brand "href="https://github.com/nlpia/nlpia-bot">Github</a>
    </nav>
</div>

<div class='jumbotron'>
        {% block body_block%}
        {% endblock %}
</div>

 <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

qarysite/qary_app/templates/qary_app/first_app_detail.html
{% extends 'qary_app/qary_app_base.html'%}
{% block body_block%}

<div class=jumbotron>
   <h2>Welcome to a list of all detail post</h2>
    <h3>Posts detail: </h3>
    <p>Author: {{post_detail.author}}</p>
    <p>Title: {{post_detail.title}}</p>
    <p>{{post_detail.text}}</p>
</div>
{% endblock %}

qarysite/qary_app/templates/qary_app/post_list.html
{% extends 'qary_app/qary_app_base.html'%}
{% block body_block%}

<h2>Welcome to a list of all Posts</h2>
<ol>
    {% for p in posts %}
    <h4><li><a href="{{p.id}}">{{p.title}}</a></li></h4>
    {%endfor%}
</ol>

{% endblock %}

qarysite/templates/answer.html
{% extends 'home.html'%}
{% block body_block%}

<div class='jumbotron'>
<h3><h2>Your question: </h2>{{Question}}</h3>
<h3><h2>Bot answer: </h2>{{insert}}</h3>
<p><a href="{% url 'question'%}">Ask another question</a></p>
</div>

{% endblock %}

qarysite/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Django-Project</title>
</head>
<body>
<div class="navbar navbar-dark bg-dark">
    <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'qary_app:list'%}">Posts</a>
    <a class="navbar-brand "href="{% url 'admin:index'%}">Admin</a>
    <a class="navbar-brand "href="{% url 'question'%}">Bot</a>
    <a class="navbar-brand "href="https://github.com/nlpia/nlpia-bot">Github</a>
    </nav>
</div>

<div class='jumbotron'>
        {% block body_block%}
        {% endblock %}
</div>

 <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

qarysite/templates/question.html
{% extends 'home.html'%}
{% block body_block%}

<div class='jumbotron'>

    <form action = "" method = "get"> 
    <h3><label >Ask the bot a question: </label> </h3>
    <input type="text" name="n"> 
    <input type="submit" value="submit" > 
    <p><a href="{% url 'answer'%}">click for answer</a></p>
    </form>
</div>

{% endblock %}