swotsite/manage_project/manage_project/urls.py
from django.contrib import admin
from django.urls import path
from swot import views
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^swot/', include('swot.urls', namespace='swot')),

]

swotsite/manage_project/swot/urls.py
from django.conf.urls import url
from swot import views
from django.urls import path

app_name = 'swot'

urlpatterns = [

    url(r'^$', views.PurposeListView.as_view(), name='list'),

    url(r'^(?P<pk>\d+)/$',
        views.PurposeDetailView.as_view(), name='detail'),

    url(r'^create/$', views.PurposeCreateView.as_view(), name='create'),

    url(r'^update/(?P<pk>\d+)/$',
        views.PurposeUpdateView.as_view(), name='update'),

]

swotsite/manage_project/swot/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Purpose(models.Model):
    purpose = models.CharField(max_length=256)

    def __str__(self):
        return self.purpose

    def get_absolute_url(self):
        return reverse('swot:detail', kwargs={'pk': self.pk})


class SWOT(models.Model):
    strength = models.CharField(max_length=256, blank=True, default=None)
    strength_rate = models.PositiveIntegerField(null=True, default=0)
    weaknesses = models.CharField(max_length=256, blank=True, default=None)
    weaknesses_rate = models.PositiveIntegerField(null=True, default=0)
    oportinuties = models.CharField(max_length=256, blank=True, default=None)
    oportinuties_rate = models.PositiveIntegerField(null=True, default=0)
    threats = models.CharField(max_length=256, blank=True, default=None)
    threats_rate = models.PositiveIntegerField(null=True, default=0)
    strategy = models.TextField(blank=True, default=None)
    purpose = models.ForeignKey(
        Purpose, on_delete=models.CASCADE, related_name='s')

    def __str__(self):
        return self.strength

    # def get_absolute_url(self):
    #     return reverse('swot:detail', kwargs={'pk': self.pk})

swotsite/manage_project/to_do/models.py
from django.db import models

# Create your models here.

swotsite/manage_project/swot/views.py
from django.shortcuts import render
from . import models
from django.urls import reverse
from django.views.generic import (View,
                                  TemplateView, ListView,
                                  DetailView, UpdateView,
                                  CreateView, DeleteView)


# Create your views here.


class IndexView(TemplateView):
  template_name = 'index.html'


class PurposeListView(ListView):
  context_object_name = 'purposes'
  model = models.Purpose


class PurposeDetailView(DetailView):
  context_object_name = 'purpose_detail'
  model = models.Purpose
  template_name = 'swot/purpose_detail.html'


class PurposeCreateView(CreateView):
  fields = ('purpose',)
  model = models.Purpose


class PurposeUpdateView(CreateView):
  fields = ('purpose',)
  model = models.Purpose

swotsite/manage_project/to_do/views.py
from django.shortcuts import render

# Create your views here.

swotsite/manage_project/swot/templates/swot/purpose_detail.html
{% extends 'swot/swot_base.html'%}
{% block body_block %}

<div class='jumbotron'>


<h2>Purpose detail:</h2>
<p>Purpose: {{purpose_detail.purpose}}</p>

<table class="table table-striped table-dark">  
<tr>
    <th>Strength</th>
    <th>Weaknesses</th>
    <th>Oportinuties</th>
    <th>Threats</th>

</tr>

<tr>
    
<td>{% for s in purpose_detail.s.all%}
<p>{{s.strength}}</p>
{% endfor%}
</td>



<td>{% for s in purpose_detail.s.all%}
<p>{{s.weaknesses}}</p>
{% endfor%}
</td>



<td>{% for s in purpose_detail.s.all%}
<p>{{s.oportinuties}}</p>
{% endfor%}
</td>



<td>{% for s in purpose_detail.s.all%}
<p>{{s.threats}}</p>
{% endfor%}
</td>


</tr>
</table>



<h3>Strategy</h3>
{% for s in purpose_detail.s.all%}
<p>{{s.strategy}}</p>
{% endfor%}


</div>




 <div class="container">
    <p><a class='btn btn-secondary'href="{% url 'swot:update' pk=purpose_detail.pk %}"></a>Update</p>
    
</div>

{% endblock %}

swotsite/manage_project/swot/templates/swot/purpose_form.html
{% extends 'swot/swot_base.html'%}
{% block body_block %}

<h1>
    {% if not form.instance.pk%}
    Create Purpose
    {% else %}
    Update Purpose
    {% endif%}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-secondary" value="Submit">
</form>





{% endblock %}

swotsite/manage_project/swot/templates/swot/purpose_list.html
{% extends 'swot/swot_base.html'%}
{% block body_block %}

<div>

<h1>Welcome to a list of all the Purposes!</h1>

<ol>   
    {% for p in purposes %}
    <h3><font size="5" color="#D35400">
      <li><a href="{{p.id}}"><font size="5" color="#D35400">{{p.purpose}}</font></a></li>
  </font>
  </h3>
    {% endfor %}   
</ol>
</div>


{% endblock %}

swotsite/manage_project/swot/templates/swot/swot_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'swot/main.css' %}">

<title>Base</title>
</head>

    <body>
        <div class="navbar navbar-dark bg-dark">
            <nav class="navbar navbar-dark bg-dark">
            
            <a class="navbar-brand" href="{% url 'swot:list'%}">Purpose</a>
            <a class="navbar-brand "href="{% url 'admin:index'%}">Admin</a>
            <a class="navbar-brand "href="{% url 'swot:create'%}">Create</a>
                    
            
                
            </nav>
        </div>

        <div class="container-fluid">
       {% block body_block%}
        {% endblock %}
        </div>

       

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>
</html>

swotsite/manage_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
        <head>
            <meta charset="utf-8">
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
               <link rel="stylesheet" type="text/css" href="{% static 'swot/main.css' %}">

                <title>Base</title>
        </head>


        <body> 
       <div class="navbar navbar-dark bg-dark">
            <nav class="navbar navbar-dark bg-dark">
            
            <a class="navbar-brand" href="{% url 'swot:list'%}">Purpose</a>
            <a class="navbar-brand "href="{% url 'admin:index'%}">Admin</a>
            <a class="navbar-brand "href="{% url 'swot:create'%}">Create</a>
            </nav>
       
       </div>
        
            <div class="container-fluid">
            {% block body_block%}

            {% endblock %}
            </div>

            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
     

        </body>
</html>

swotsite/manage_project/templates/index.html
{% extends "base.html"%}
{% block body_block%}
<div class='jumbotron'>
    <h1>Home page</h1>
    
</div>

{% endblock %}